name: yb_flutter_lib_ui
description: flutter quick ui lib, like button、text、image、redCount、bg_decoration...
version: 0.0.2+14
homepage: https://github.com/crazycoding7/flutter_lib_ui

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.2.1
  flutter_screenutil: ^5.5.2
  liquid_swipe: ^3.0.0
  common_utils: ^2.0.2
  flutter_smart_dialog: ^4.5.3
  fluttertoast: ^8.0.8
  timer_count_down: ^2.2.0
  get: 4.6.4
  flutter_html: 3.0.0-alpha.5
  flutter_switch: ^0.3.2
  keyboard_actions: 4.1.0
  yb_flutter_quill: ^5.4.1
  image_picker: ^0.8.5+3
  badges: ^2.0.2
  yb_pull_to_refresh: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - images/common_checkbox_null_icon.png
    - images/common_checkbox_selected_icon.png
    - images/common_to_right.png
    - images/page_me_center.png
    - images/page_patient_visit.png
    - images/bank_card_add.png
    - images/common_search_icon.png
    - images/common_edit_delete.png
    - images/common_empty_icon.png
    - images/common_title_back_icon.png
    # main page
    - images/page_main_tab_normal.png
    - images/page_main_tab_selected.png
    - images/page_me_tab_normal.png
    - images/page_me_tab_selected.png
    - images/page_patient_tab_normal.png
    - images/page_patient_tab_selected.png
    - images/page_home_career_guide.png
    # common images
    - images/common_title_back_icon.png
    - images/common_title_back_black_icon.png
    - images/common_to_right.png
    - images/common_star_tip_icon.png
    - images/common_search_icon.png
    - images/common_search_radio_normal_icon.png
    - images/common_search_radio_selected_icon.png
    - images/common_red_dot_delete.png
    - images/common_edit_icon.png
    - images/common_radio_null.png
    - images/common_radio_selected.png
    - images/common_edit_delete.png
    - images/common_checkbox_selected_icon.png
    - images/common_checkbox_null_icon.png
    - images/common_empty_icon.png
    - images/common_empty_patient_icon.png
    - images/common_tip.png
    - images/common_tip_yellow.png
    - images/common_to_down_72.png
    - images/common_to_right_72.png
    - images/common_bubble_icon.png
    - images/common_help_grey.png
    - images/common_to_down_grey.png
    - images/common_to_right_black.png
    - images/common_ok.png
    - images/common_location_icon.png
    - images/common_check_green.png
    - images/common_good.png
    - images/common_see.png
    - images/common_to_right_white.png
    - images/common_default_avatar.png
    - images/common_video_start_icon.png
    - images/common_checkbox_selected.png
    - images/common_item_edit.png
    - images/common_appbar_more.png
    - images/common_check_circle.png
    - images/common_uncheck_circle.png
    - images/common_to_right_63.png
    - images/common_shop_bbjd_icon.png
    - images/common_shop_jkpg_icon.png
    - images/common_shop_yszx_icon.png
    - images/common_shop_yyzd_icon.png
    - images/common_right_63_icon.png
    - images/common_select_down.png
    # task manager
    - images/task_work_icon.png
    - images/task_study_icon.png
    - images/page_school_tab_normal.png
    - images/page_school_tab_selected.png
    - images/page_task_home_type_money.png
    - images/page_task_home_type_score.png
    # home page
    - images/page_home_title_icon.png
    - images/page_home_title_right_sao_icon.png
    - images/page_home_head_icon_default.png
    - images/page_home_qr_code_icon.png
    - images/page_home_cer_icon.png
    - images/page_home_info_people_say.png
    - images/page_home_info_prescription_say.png
    - images/page_home_menu_medicine_suggest.png
    - images/page_home_menu_online_counsel.png
    - images/page_home_menu_online_inquiry.png
    - images/page_home_menu_online_ask.png
    - images/page_home_menu_online_video.png
    - images/home_shop_setting.png
    - images/home_shop_task.png
    - images/home_shop_visit.png
    - images/home_shop_medicine.png
    - images/guide_platform_back.png
    - images/guide_platform_doctor.png
    - images/illness_plan_create_icon.png
    - images/home_message_bg.png
    # medicine suggest page
    - images/page_medicine_suggest_result_no_pass_bg.png
    - images/page_medicine_suggest_result_no_pass_icon.png
    - images/page_medicine_suggest_result_pass_bg.png
    - images/page_medicine_suggest_result_pass_icon.png
    - images/page_medicine_suggest_result_passing_bg.png
    - images/page_medicine_suggest_result_passing_icon.png
    - images/page_medicine_suggest_detail_bg.png
    - images/page_medicine_suggest_add_icon.png
    - images/page_guide_icon.png
    - images/page_prescription_tip_check_pass.png
    - images/page_prescription_tip_checking.png
    - images/add_medicine_icon.png
    # 我的患者
    - images/service_line_online_icon.png
    - images/service_line_pass_icon.png
    - images/ipm_money_system.png
    - images/checkbox_off_icon.png
    - images/checkbox_on_icon.png
    - images/common_selected_icon.png
    - images/switch_off_icon.png
    - images/switch_on_icon.png
    - images/common_tip_down.png
    - images/common_tip_up.png
    - images/common_close_black_icon.png
    # To add assets to your application, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    - images/page_main_tab_normal.png
    - images/page_main_tab_selected.png
    - images/page_me_tab_normal.png
    - images/page_me_tab_selected.png
    - images/page_patient_tab_normal.png
    - images/page_patient_tab_selected.png
    - images/page_patient_visit.png
    - images/page_home_title_icon.png
    - images/page_home_title_right_sao_icon.png
    - images/page_message_success.png
    - images/page_password_setting_dismiss.png
    - images/certify_3.png
    - images/page_certify_message.png
    - images/page_certify_patient.png
    - images/page_certify_qrcode.png
    - images/page_certify_prescription.png
    - images/page_certify_message_green.png
    - images/page_certify_patient_green.png
    - images/page_certify_qrcode_green.png
    - images/page_certify_prescription_green.png
    - images/page_certify_camera.png
    - images/page_login_clear.png
    - images/page_certify_warning.png
    - images/page_certify_require_warning.png
    - images/page_certify_idcard_front.png
    - images/page_certify_idcard_back.png
    - images/page_certify_card_common.png
    - images/add_hospital.png
    - images/page_me_settings.png
    - images/page_me_forward.png
    - images/page_me_forward_grey.png
    - images/page_me_center.png
    - images/page_me_forward_orange.png
    - images/page_me_center.png
    - images/page_me_qrcode.png
    - images/page_me_service_list.png
    - images/page_me_service_setting.png
    - images/page_me_call.png
    - images/page_me_help_icon.png
    - images/page_me_address_icon.png
    - images/page_me_question_add_icon.png
    - images/page_me_warning.png
    - images/page_me_money_detail.png
    - images/page_me_get_money.png
    - images/page_me_phone.png
    - images/page_me_calendar.png
    - images/default_tou.jpg
    - images/default_qrcode.png
    - images/page_me_detail_orange.png
    - images/page_me_detail_blue.png
    - images/page_me_service_detail_question.png
    - images/page_income_up_background.png
    - images/page_income_empty.png
    - images/income_with_draw.png
    - images/income_with_draw_fail.png
    - images/bank_bg_jianshe.png
    - images/bank_bg_beijing.png
    - images/bank_bg_nongye.png
    - images/bank_bg_zhaoshang.png
    - images/bank_icon_jianshe.png
    - images/bank_icon_beijing.png
    - images/bank_icon_nongye.png
    - images/bank_icon_zhaoshang.png
    - images/bank_card_add.png
    - images/page_home_scan_qrcode.png
    - images/page_home_scan_image.png
    - images/product_detection_report_analyse.png
    #个人中心
    #im相关
    - images/im_message_voice.png
    - images/im_message_voice_white.png
    - images/im_message_document_white.png
    - images/im_message_prescription_white.png
    - images/im_message_reject_white.png
    - images/im_message_document_blue.png
    - images/im_message_warning_left.png
    - images/im_message_reject_red.png
    - images/im_message_document_edit_blue.png
    - images/im_keyboard_black.png
    - images/im_keyboard_more.png
    - images/im_keyboard_phrase.png
    - images/im_keyboard_document.png
    - images/im_keyboard_advice.png
    - images/im_keyboard_photo.png
    - images/im_keyboard_camera.png
    - images/im_keyboard_video.png
    - images/im_keyboard_prescription.png
    - images/im_keyboard_form.png
    - images/im_keyboard_examine.png
    - images/im_dialog_video.png
    - images/im_dialog_audio.png
    - images/im_patient_default_icon.png
    - images/im_phrase_add.png
    - images/im_message_visit_receive.png
    - images/im_message_visit_send.png
    - images/im_message_video.png
    - images/im_message_audio.png
    - images/im_document_background.png
    - images/im_avatar_robot.png
    - images/test_line_first.png
    - images/test_line_other.png
    - images/test_bg_1.png
    - images/test_bg_2.png
    - images/test_score_bg.png
    - images/me_change_account_tip.png
    #欢迎页
    - images/welcome_guide_icon_1.png
    - images/welcome_guide_icon_2.png
    - images/welcome_guide_icon_3.png
    - images/welcome_logo.png
    - images/welcome_menu_back.png
    - images/welcome_menu_money.png
    - images/welcome_menu_normal.png
    - images/welcome_menu_video.png
    - images/welcome_guide_base_icon.png
    - images/welcome_guide_check_icon.png
    - images/welcome_guide_info_icon.png
    - images/welcome_guide_people_icon.png
    - images/welcome_guide_money_tip_icon.png
    - images/welcome_guide_number_1.png
    - images/welcome_guide_number_01.png
    - images/welcome_guide_number_2.png
    - images/welcome_guide_number_02.png
    - images/welcome_guide_number_3.png
    - images/welcome_guide_number_03.png
    - images/welcome_guide_number_4.png
    #评价页
    - images/comment_star_empty.png
    - images/comment_star_half.png
    - images/comment_star_full.png
    - images/common_status_cancel.png
    - images/common_status_doing.png
    - images/video_call_cancel_icon.png

    #患教资料
    - images/patient_article_item_check.png
    - images/patient_article_item_comment.png
    - images/patient_article_item_like.png
    - images/patient_article_item_share.png
    - images/patient_article_share.png
    - images/patient_article_edit.png
    - images/patient_article_delete.png
    - images/patient_article_comment_like.png
    - images/patient_article_comment_unlike.png
    - images/patient_tab_icon.png
    - images/patient_tab_icon_white.png
    - images/patient_base_info_background.png
    - images/patient_health_icon_weight.png
    - images/patient_health_icon_blood_glucose.png
    - images/patient_health_icon_blood_pressure.png
    - images/patient_health_icon_heart_rate.png
    - images/patient_health_icon_list.png
    - images/patient_health_icon_result_low.png
    - images/patient_health_icon_result_normal.png
    - images/patient_health_icon_result_high.png
    - images/patient_tab_icon_base_unselect.png
    - images/patient_tab_icon_base_select.png
    - images/patient_tab_icon_health_unselect.png
    - images/patient_tab_icon_health_select.png
    - images/patient_tab_icon_report_unselect.png
    - images/patient_tab_icon_report_select.png
    - images/patient_tab_icon_service_unselect.png
    - images/patient_tab_icon_service_select.png
    - images/patient_tab_icon_test_unselect.png
    - images/patient_tab_icon_test_select.png
    - images/visit_add_patient.png
    - images/visit_date_add.png
    - images/visit_date_delete.png
    - images/visit_add_header.png