name: yb_flutter_lib_ui
description: Dart package which manages the api domain.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.2.1
  flutter_screenutil: 5.5.2
  liquid_swipe: ^3.0.0
  common_utils: ^2.0.2
  flutter_smart_dialog: ^4.5.3
  fluttertoast: ^8.0.8
  timer_count_down: ^2.2.0
  get: 4.6.4


flutter:
  uses-material-design: true
  assets:
    - images/common_checkbox_null_icon.png
    - images/common_checkbox_selected_icon.png
    - images/common_to_right.png
    - images/page_me_center.png
    - images/page_patient_visit.png
    - images/bank_card_add.png
    - images/common_search_icon.png
    - images/common_edit_delete.png
    - images/common_empty_icon.png
    - images/common_title_back_icon.png